# Generated by Django 5.0.2 on 2024-02-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filter_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('rooms', models.IntegerField(blank=True, max_length=1)),
                ('parking', models.IntegerField(blank=True, max_length=1)),
                ('price', models.IntegerField(blank=True)),
                ('metr', models.IntegerField(blank=True)),
            ],
        ),
    ]
