# Generated by Django 5.0.2 on 2024-02-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter_table',
            name='parking',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filter_table',
            name='rooms',
            field=models.IntegerField(blank=True),
        ),
    ]
